Repository pwndbg/pwndbg, pull requests merged in 2025-04, with the labels that each got.

#2873 Add basic support for s390x
  pwndbg/aglib/disasm/__init__.py
  pwndbg/aglib/disasm/instruction.py
  pwndbg/dbg/gdb/__init__.py
  pwndbg/emu/emulator.py
  pwndbg/lib/arch.py
  pwndbg/lib/regs.py
Labels: feature

#2880 bump: lldb_19 -> lldb_20
  flake.nix
Labels: dependencies

#2878 cleanup: fix command names '_' with '-'
  DEVELOPING.md
  docs/commands/memory/vmmap.md
  profiling/benchmark_vis_heap_chunks/README.md
  pwndbg/aglib/heap/__init__.py
  pwndbg/aglib/stack.py
  pwndbg/aglib/vmmap_custom.py
  pwndbg/auxv.py
  pwndbg/commands/__init__.py
  pwndbg/commands/vmmap.py
  pwndbg/lib/tips.py
Labels: code cleanup

#2766 Upgrade to Capstone V6
  nix/pyenv.nix
  pwndbg/aglib/disasm/__init__.py
  pwndbg/aglib/disasm/aarch64.py
  pwndbg/aglib/disasm/arch.py
  pwndbg/aglib/disasm/arm.py
  pwndbg/aglib/disasm/instruction.py
  pwndbg/aglib/disasm/mips.py
  pwndbg/aglib/disasm/riscv.py
  pwndbg/emu/emulator.py
  pwndbg/lib/disasm/helpers.py
  pwndbg/lib/regs.py
  pyproject.toml
  tests/qemu-tests/tests/user/test_aarch64.py
  tests/qemu-tests/tests/user/test_arm.py
  tests/qemu-tests/tests/user/test_mips.py
  tests/qemu-tests/tests/user/test_riscv64.py
  tests/unit-tests/test_bit_math.py
  uv.lock
Labels: enhancement, dependencies

#2879 Small Refactor to DisassemblyAssistant
  pwndbg/aglib/__init__.py
  pwndbg/aglib/disasm/__init__.py
  pwndbg/aglib/disasm/aarch64.py
  pwndbg/aglib/disasm/arch.py
  pwndbg/aglib/disasm/arm.py
  pwndbg/aglib/disasm/disassembly.py
  pwndbg/aglib/disasm/mips.py
  pwndbg/aglib/disasm/riscv.py
  pwndbg/aglib/disasm/x86.py
  pwndbg/aglib/nearpc.py
  pwndbg/aglib/next.py
  pwndbg/aglib/tls.py
  pwndbg/arguments.py
  pwndbg/commands/branch.py
  pwndbg/commands/context.py
  pwndbg/commands/dev.py
  pwndbg/commands/dumpargs.py
  pwndbg/commands/rop.py
  pwndbg/commands/search.py
  pwndbg/emu/emulator.py
  pwndbg/enhance.py
  tests/qemu-tests/tests/user/test_aarch64.py
Labels: code cleanup

#2892 Remove support for GDB <= 9.x
  pwndbg/dbg/gdb/__init__.py
Labels: code cleanup

#2891 Add aliases for commands with '_' to inform about the change to '-'
  pwndbg/dbg/gdb/__init__.py
Labels: code cleanup

#2885 Add capstone for loongarch64
  pwndbg/aglib/disasm/disassembly.py
  pwndbg/aglib/disasm/instruction.py
  pwndbg/aglib/disasm/loongarch64.py
Labels: enhancement

#2875 Cleanup parameters and autogenerate doc pages for them
  docs/commands/index.md
  docs/commands/pwndbg/heap-config.md
  docs/configuration/config.md
  docs/configuration/heap.md
  docs/configuration/index.md
  docs/configuration/theme.md
  docs/stylesheets/extra.css
  lint.sh
  mkdocs.yml
  pwndbg/aglib/disasm/arch.py
  pwndbg/aglib/heap/__init__.py
  pwndbg/aglib/kernel/vmmap.py
  pwndbg/aglib/stack.py
  pwndbg/auxv.py
  pwndbg/color/theme.py
  pwndbg/commands/config.py
  pwndbg/commands/context.py
  pwndbg/commands/hexdump.py
  pwndbg/commands/ptmalloc2.py
  pwndbg/gdblib/events.py
  pwndbg/glibc.py
  pwndbg/integration/binja.py
  pwndbg/lib/config.py
  pwndbg/ui.py
  scripts/_gen_command_docs.py
  scripts/_gen_configuration_docs.py
  scripts/_gen_docs_generic.py
  scripts/docs-live.sh
  scripts/docs.sh
  scripts/generate_docs.sh
  scripts/verify_docs.sh
Labels: code cleanup

#2911 portable: make libiconv static
  flake.nix
Labels: bug

#2807 Express context saved to the stack + Arm Cortex M Exception return address resolution
  docs/commands/index.md
  docs/commands/memory/dump-register-frame.md
  pwndbg/aglib/disasm/arm.py
  pwndbg/aglib/saved_register_frames.py
  pwndbg/commands/__init__.py
  pwndbg/commands/saved_register_frames.py
Labels: feature

#2914 Update zig 0.10.1->0.13.0
  setup-dev.sh
  tests/gdb-tests/tests/binaries/makefile
Labels: dependencies

#2916 Fix parsing gaps in command line history
  pwndbg/dbg/gdb/__init__.py
Labels: bug

#2929 tests: remove netcat-openbsd dependency
  nix/devshell.nix
  setup-dev.sh
  tests/gdb-tests/tests/test_command_procinfo.py
Labels: code cleanup

#2934 Fixes #2924: docker legacy warning
  Dockerfile
  Dockerfile.arch
  Dockerfile.lldb
Labels: code cleanup
